// Beholder per-lane extraction prompts — PORTED from the DataGen pipeline (xattr_v1: cross-attribution rules).
// The trained model (v7/tkaug-xa1) was trained+evaluated on THESE prompts; runtime MUST send them (train==inference).
// worn: rm_v1 removal + owner-binding (R1)/persona-sink (R3)/depiction+mount (R5); wounds: +perception-frame (R2);
// species: +own-body (R4). Regenerate from the pipeline (BEHOLDER_WORN_PROMPT=xattr_v1); do not hand-edit.
export const SHORT_PASS_PROMPTS = {
  worn: "You extract ONLY worn clothing/items. From THIS turn's prose, emit what changed about characters' WORN items.\nTrack only the persona (output as \"self\") and characters with a proper name. Use only valid body slots.\n- item = simplest singular noun; material/color/damage go in their own fields (\"leather jacket\" -> {\"item\":\"jacket\",\"material\":\"leather\"}).\n- Multi-slot garments cover EVERY slot they occupy (a dress -> chest+back+waist+both legs+both shoulders; pants -> waist+both legs; gloves -> both hands; boots -> both feet).\n- Descriptive establishment (\"she wears X\", \"dressed in Y\", \"an outfit of Z\") IS a change.\n- When a character REMOVES / takes off a specific garment (or changes OUT of it), emit \"worn_remove\": [\"<item>\"] on each slot it occupied \u2014 name the garment. Only remove what the prose SHOWS coming off; garments not mentioned as removed STAY on.\n- Bind each garment to its OWNER: \"his/her/their X\" routes to that clause's subject/possessor, NOT the nearest name or the persona; on ambiguity prefer a NAMED character over self.\n- Items shown only in a portrait/photo/screen/mirror, or worn by a mount or vehicle (barding, a mech's canopy), belong to NO real character \u2014 omit them.\n- Do NOT invent items the prose doesn't state; do NOT re-emit unchanged items already in the state.\n- damage is structural only (torn/cracked/broken), never dirt or blood: pristine|damaged|broken.\nOutput JSON only, exactly one of:\n{\"changed\": false}\n{\"changed\": true, \"delta\": {\"<char>\": {\"body\": {\"<slot>\": {\"worn\": [{\"item\": \"<noun>\", \"material\": \"<opt>\", \"color\": \"<opt>\", \"damage\": \"pristine\"}], \"worn_remove\": [\"<item>\"]}}}}}\nUse \"worn\": [] to clear a slot entirely (fully bare).",
  wounds: "You extract ONLY wounds/injuries. From THIS turn's prose, emit what changed about characters' injuries.\nTrack only the persona (output as \"self\") and named characters. Use only valid body slots.\n- Emit a wound for ANY injury evident this turn: newly inflicted OR already-sustained/described (a character shown bleeding, an old wound reopening), and on ANY named character \u2014 not just live on-screen hits to the persona.\n- The subject of a perception verb (sees/notices/watches/observes) is the OBSERVER, not the owner \u2014 bind a perceived wound to the party it is ON, never the observer/self. Keep counts as stated (\"two cuts\" = two). An old scar merely recalled, not freshly wounded, is not a change.\n- text = short injury phrase (\"gash\", \"burn\", \"stab\", \"fracture\").\n- severity: minor | serious | critical.  bleeding: true | false.\nOutput JSON only, exactly one of:\n{\"changed\": false}\n{\"changed\": true, \"delta\": {\"<char>\": {\"body\": {\"<slot>\": {\"wounds\": [{\"text\": \"<phrase>\", \"severity\": \"minor\", \"bleeding\": false}]}}}}}",
  holding: "You extract ONLY items HELD in a hand. From THIS turn's prose, emit what changed about what characters hold.\nTrack only the persona (output as \"self\") and named characters. Only left_hand / right_hand.\n- Held = grasped/wielded right now (sword in hand, a cup, a phone). NOT worn \u2014 a sheathed sword is worn at the waist, not held.\n- Picking up = set holding; setting down / sheathing / putting on = clear holding ({}).\nOutput JSON only, exactly one of:\n{\"changed\": false}\n{\"changed\": true, \"delta\": {\"<char>\": {\"body\": {\"right_hand\": {\"holding\": {\"item\": \"<noun>\"}}}}}}\nUse \"holding\": {} to clear a hand.",
  species: "You extract ONLY species. From THIS turn's prose, emit a character's species when it is first established or changes.\nTrack only the persona (output as \"self\") and named characters.\n- Assign a species ONLY from a creature-kind predicated of THIS character's OWN body (a living gargoyle/android/lamia that IS the character). NEVER from a statue/carving, a species named only as a topic/faction/blood-status, or a scenery creature \u2014 omit those.\n- For non-human species with extra anatomy, also emit empty exotic-slot stubs as {}: tail, hind_left_leg, hind_right_leg, hind_left_foot, hind_right_foot.\nOutput JSON only, exactly one of:\n{\"changed\": false}\n{\"changed\": true, \"delta\": {\"<char>\": {\"species\": \"<species>\", \"body\": {\"tail\": {}}}}}",
  flags: "You extract ONLY bare and missing flags. From THIS turn's prose, emit what changed.\nTrack only the persona (output as \"self\") and named characters. Use only valid body slots.\n- bare = true when a slot becomes exposed/naked (clothing removed and nothing underneath).\n- missing = true when a body part is severed/amputated/absent.\nOutput JSON only, exactly one of:\n{\"changed\": false}\n{\"changed\": true, \"delta\": {\"<char>\": {\"body\": {\"<slot>\": {\"bare\": true, \"missing\": false}}}}}",
};
export const LANE_ORDER = ["worn", "wounds", "holding", "species", "flags"];
// Prompt-lineage tag the trained model was trained+evaluated on (BEHOLDER_WORN_PROMPT).
// Surfaced in the Doctor so the "System prompt" vital names the actual prompt in use.
export const SHORT_PASS_TAG = "xattr_v1";
